on:
  push:
    branches:
      - 'main'
  pull_request:

name: CI

jobs:
  format:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        target:
          - oxide-auth
          - oxide-auth-actix
          - oxide-auth-async
          - oxide-auth-axum
          - oxide-auth-db
          - oxide-auth-iron
          - oxide-auth-poem
          # TODO: Enable when updated to Rocket 0.5
          # https://github.com/197g/oxide-auth/issues/131
          # - oxide-auth-rocket
          - oxide-auth-rouille
          - db-example
          - actix-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustfmt
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-format-${{ hashFiles('**/Cargo.lock') }}
      - name: Check code formatting
        run: cargo fmt --package ${{ matrix.target }} -- --check
  lint:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        target:
          - oxide-auth
          - oxide-auth-actix
          - oxide-auth-async
          - oxide-auth-axum
          - oxide-auth-db
          - oxide-auth-iron
          - oxide-auth-poem
          # TODO: Enable when updated to Rocket 0.5
          # https://github.com/197g/oxide-auth/issues/131
          # - oxide-auth-rocket
          - oxide-auth-rouille
          - db-example
          - actix-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-lint-${{ hashFiles('**/Cargo.lock') }}
      - name: Run Clippy
        run: cargo clippy --package ${{ matrix.target }} --no-deps --all-targets --keep-going -- -Dwarnings
  semver:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
        target:
          - oxide-auth
          - oxide-auth-actix
          - oxide-auth-async
          - oxide-auth-axum
          - oxide-auth-db
          - oxide-auth-iron
          - oxide-auth-poem
          # TODO: Enable when updated to Rocket 0.5
          # https://github.com/197g/oxide-auth/issues/131
          # - oxide-auth-rocket
          - oxide-auth-rouille
          - db-example
          - actix-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-semver-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo install cargo-semver-checks --locked
      - name: Run cargo semver checks
        run: cargo semver-checks --package ${{ matrix.target }} --verbose
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - dev
          - release
        toolchain:
          - stable
          - beta
          - nightly
        target:
          - oxide-auth
          - oxide-auth-actix
          - oxide-auth-async
          - oxide-auth-axum
          - oxide-auth-db
          - oxide-auth-iron
          - oxide-auth-poem
          # TODO: Enable when updated to Rocket 0.5
          # https://github.com/197g/oxide-auth/issues/131
          # - oxide-auth-rocket
          - oxide-auth-rouille
          - db-example
          - actix-example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-build-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Build "${{ matrix.target }}" with "${{ matrix.profile }}" profile
        run: cargo build --verbose --all-targets --profile ${{ matrix.profile }} --package ${{ matrix.target }}
      - name: Run ${{ matrix.target }} tests with "${{ matrix.profile }}" profile
        run: cargo test --verbose --profile ${{ matrix.profile }} --package ${{ matrix.target }}
